### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by victorh800** [bblanchon/ArduinoJson-vs-Arduino_JSON#1]
in your [blog post](https://arduinojson.org/2019/11/19/arduinojson-vs-arduino_json/#performance), the link at "Tare" is broken. it misses the `tree/master/` part.

**Comment by bblanchon** [comment]
Fixed.
@victorh800, thank you very much for reporting this issue.

**Comment by victorh800** [comment]
anytime, Benoit.
by the way, I just realized this is the first time I report issue #1 in a public repo. it's like writing "FIRST!!!11!" in a blog post comment. 😉
